# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_and_test do
    scan(
    scheme: "MBStockTracker",
    device: "iPhone 17 Pro",
    code_coverage: true,
    output_directory: "./fastlane/test_output",
    output_types: "html,json"
  )
  end
end
